name       : python-versioneer
version    : 0.28
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/v/versioneer/versioneer-0.28.tar.gz : 7175ca8e7bb4dd0e3c9779dd2745e5b4a6036304af3f5e50bd896f10196586d6
homepage   : https://github.com/python-versioneer/python-versioneer
license    : Unlicense
component  : programming.python
summary    : version-string management for VCS-controlled trees
description: |
    This is a tool for managing a recorded version number in setuptools-based python projects. The goal is to remove the tedious and error-prone "update the embedded version string" step from your release process. Making a new release should be as easy as recording a new tag in your version-control system, and maybe making new tarballs.
builddeps  :
    - python-build
    - python-installer
build      : |
    %python3_setup
install    : |
    %python3_install
